In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4])
print(array)                                #[1 2 3 4]

[1 2 3 4]


In [3]:
array = array*3                             #array = array*2
print(array)     

[ 3  6  9 12]


In [4]:
zero_dim_array = np.array('a')
print(zero_dim_array)                              #a
print(zero_dim_array.ndim)                         #0                               0 dimentional array

a
0


In [5]:
multi_array= np.array([[[1 ,2 ,3 ],[4 ,5 ,6 ],[7 ,8 ,9 ]],
                       [[10,11,12],[13,14,15],[16,17,18]],
                       [[19,20,21],[22,23,24],[25,26,27]]])
print(multi_array.ndim)                             #3
print(multi_array[0,0,0])                           #1
print(multi_array.shape)                            #(3,3,3)

3
1
(3, 3, 3)


In [6]:
slicing_array = np.array([
    [ 1, 2, 3, 4],
    [ 5, 6, 7, 8],
    [ 9,10,11,12],
    [13,14,15, 16]
])

print(slicing_array[:-1])                                 #[[ 1  2  3  4][ 5  6  7  8][ 9 10 11 12]]


print(slicing_array[::2])                             #slicing same as string slicing

print(slicing_array[:,0])                                   #[ 1  5  9 13]
print(slicing_array[:,1])                                   #[ 2  6 10 14]
print(slicing_array[:,-1])                                  #[ 4  8 12 16]




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 1  5  9 13]
[ 2  6 10 14]
[ 4  8 12 16]


In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])


# arr[-1::-1,-1::-1]                    #array([[90, 80, 70],
                                            # [60, 50, 40],
                                            # [30, 20, 10]])     





array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# arr[0:3,2:0:-1]
# arr[::-1, 1:3]

array([[10, 11],
       [ 6,  7],
       [ 2,  3]])